### ISSUE TITLE
Event loop not supported

### ISSUE THREAD

**Issue by DouglasHennrich** [TheSmiths-Widgets/ts.httprequest#5]
I'm getting this error when I try to use it =l

``` js
new Alloy.Globals.HTTPRequest({
        method: "GET"
      , url: "http://www.google.com"
      , data: {}
    }).then(successHandler).catch(handleError);
```

this is what output:

``` shell
[INFO]  HTTPRequest handleSuccess for url (GET) http://www.google.com
[ERROR] : Event loop not supported.
```

**Comment by KtorZ** [comment]
Well. 
Is it possible to have the global shape of your success handler ?

**Comment by DouglasHennrich** [comment]
It is just an function with `console.log`.

Maybe titanium don't support promises?
Im running on node 4.2.2 and TiSDK 5.1.1.GA

**Comment by KtorZ** [comment]
Promises are brought by another library which is plain vanilla-javascript, thus, the issue is likely to be something else; maybe in the implementation of the module itself - we are still currently testing it. 
Are you running on iOS or Android ?

**Comment by DouglasHennrich** [comment]
Huum... `iOS`

**Comment by DouglasHennrich** [comment]
I realize that I'm getting this `Event loop not supported` error when I'm requiring the lib too

**Comment by KtorZ** [comment]
Indeed. This seems to be an issue with the promise library and
JavaScriptCore on iOS. We're trying to figure it out.

**Comment by DouglasHennrich** [comment]
Thanks =)

**Comment by PierreGUI** [comment]
Hey Douglas,
We reproduced the issue but we had no clue how to fix it, so we changed the implementation of Promises for this one: https://github.com/floatdrop/pinkie
I works as expected now.
Thanks for your feedback!

**Comment by DouglasHennrich** [comment]
Thanks for your module :D

**Comment by DouglasHennrich** [comment]
I'm sorry but it still not working ):
`Alloy.js`:

``` js
// HTTP Request
Alloy.Globals.HTTPRequest = require('ts.httprequest');
```

`main.js`:

``` js
function handleError(error){
    console.log('Error: ', JSON.stringify(error));
};

function handleSuccess(success){
    console.log('handleSuccess: ', JSON.stringify(success));
};

var request = new Alloy.Globals.HTTPRequest({
        method: "GET"
      , url: "http://www.google.com"
      , data: { }
}).then(handleSuccess).catch(handleError);
```

terminal output:

``` shell
[INFO]  HTTPRequest handleSuccess for url (GET) http://www.google.com
[ERROR] : Event loop not supported.
```

`tiapp.xml`:

``` xml
<module platform="commonjs" version="1.4.2">ts.httprequest</module>

<sdk-version>5.1.1.GA</sdk-version>
```
