### ISSUE TITLE
Still with problem Promises

### ISSUE THREAD

**Issue by DouglasHennrich** [TheSmiths-Widgets/ts.httprequest#6]
I'm sorry but it still not working ):
`Alloy.js`:

``` js
// HTTP Request
Alloy.Globals.HTTPRequest = require('ts.httprequest');
```

`main.js`:

``` js
function handleError(error){
    console.log('Error: ', JSON.stringify(error));
};

function handleSuccess(success){
    console.log('handleSuccess: ', JSON.stringify(success));
};

var request = new Alloy.Globals.HTTPRequest({
        method: "GET"
      , url: "http://www.google.com"
      , data: { }
}).then(handleSuccess).catch(handleError);
```

terminal output:

``` shell
[INFO]  HTTPRequest handleSuccess for url (GET) http://www.google.com
[ERROR] : Event loop not supported.
```

`tiapp.xml`:

``` xml
<module platform="commonjs" version="1.4.2">ts.httprequest</module>

<sdk-version>5.1.1.GA</sdk-version>
```

**Comment by KtorZ** [comment]
Sorry, we were switching between the compiled version and the standalone version for testing and a little typo slipped in :/ 
I've just tested with your example and it's work fine. Let us know if you still have any trouble, and thanks for feedbacks !

**Comment by DouglasHennrich** [comment]
You're welcome :+1:  :)

**Comment by DouglasHennrich** [comment]
@KtorZ can you provide `.zip` file, please? since Gittio it takes 1 day to update =(

**Comment by KtorZ** [comment]
The zip is correct, you can already use it (I bumped the version after creating the build :/)
I will update it later ^^

**Comment by DouglasHennrich** [comment]
oh hahaha ok Thanks
