### ISSUE TITLE
Pass more parameters?

### ISSUE THREAD

**Issue by DouglasHennrich** [TheSmiths-Widgets/ts.httprequest#8]
There's a way to pass more parameters? I want to pass some control variables to be handle on `success` of my `httprequest`, but now I'm only getting the response of the `httprequest`.
Maybe something like:

``` js
function handleSuccess(response, options){
    if(options.something) //
};

new Alloy.Globals.HTTPRequest({
        method: "POST"
      , url: config.url + 'consulta_todos.php'
      , data: _params
      , options: { something: true }
}).then(handleSuccess).catch(handleError);
```

Thanks

**Comment by PierreGUI** [comment]
Yo!
That's not possible, and is not a feature I will add.
What about binding a context?

```
function handleSuccess(response){
    if(this.something) //
};

new Alloy.Globals.HTTPRequest({
        method: "POST",
        url: config.url + 'consulta_todos.php',
        data: _params
})
    .then(handleSuccess.bind({ something: true }))
    .catch(handleError);
```

**Comment by DouglasHennrich** [comment]
never use promises before... if you say it work I will give a try =P
another question... to catch the `onloadprogress` how should I do ? An `.then(..)` before `handleSuccess` ?
Thanks

**Comment by PierreGUI** [comment]
Binding a context is pure javascript, not specific to Promises ;)

About the progress handler, it's indeed a good question because there's no way to use promise handler yet (not in Promises A+ specs...).
So you'll have to give the progress handler as a parameter:

```
function progressHandler(progress){
    Ti.API.info(progress);
};

new Alloy.Globals.HTTPRequest({
    method, url, data,
    progress: progressHandler
})
    .then(handleSuccess)
    .catch(handleError);
```

**Comment by DouglasHennrich** [comment]
Thaanks dude! :D
`bind` work by the way
